---
- name: install git
  become: yes
  apt: name=git state=latest

- name: download new version of nodejs
  become: yes
  get_url:
    url: http://deb.nodesource.com/setup_6.x
    dest: /tmp/node_setup_6.x
    mode: 0755

- name: add node.js repository
  become: yes
  shell: /tmp/node_setup_6.x

- name: install new version of nodejs
  become: yes
  apt:
    name: nodejs
    state: latest

- name: install gulp and bower
  become: yes
  npm: name={{ item }} global=yes
  with_items:
    - gulp
    - bower

- name: install npm dependencies
  shell: npm install
  args:
    chdir: {{ project_path }}

- name: install bower dependencies
  bower: path={{ project_path }}
